[build]
  # Directory to change to before starting a build
  base = "frontend"
  # Directory that contains the deploy-ready HTML files and assets (relative to base)
  publish = "dist"
  # Default build command
  command = "npm run build"

[build.environment]
  # Node version for build
  NODE_VERSION = "18"

[[redirects]]
  # Handle React Router (SPA redirects)
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  # Local development command
  command = "npm run dev"
  port = 3000
  publish = "frontend/dist"